// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaveBi.Database;

#nullable disable

namespace SpellingBee.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20240212222631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StaveBi.Model.Word", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Value");

                    b.HasIndex("Value");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
